In [1]:
from Graph_tool import multigraph as mg;
from Graph_tool import direct_multigraph as dmg;
import numpy as np
import sys
import os
import copy

In [35]:
    def pred(sel,u):
        k=0
        result=[]
        for i in sel.inInMatrix[sel.Nodes.index(u)]:
            if i==1:
                comma=int(sel.Arcs[k].find(','))
                result.append(sel.Arcs[k][1:comma])
            k+=1
        return result

In [26]:
G_13.outInMatrix[G_13.Nodes.index('2')]

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=uint32)

In [38]:
G_13.TRANSITIVECLOSURESUCC('2')

['7', '3', '2', '9', '8', '4', '5', '6', '1']

In [44]:
list(set(G_13.TRANSITIVECLOSURESUCC('2')).intersection(set(TRANSITIVECLOSUREPRED(G_13,'2'))))

['3', '2', '1', '4']

In [47]:
v=set()
    

In [48]:
type(v)

set

In [41]:
list(set((G_13.TRANSITIVECLOSURESUCC('2'))) - set(TRANSITIVECLOSUREPRED(G_13,'2')))

['7', '9', '8', '5', '6']

In [36]:
def TRANSITIVECLOSUREPRED(sel,v):
    Component=[]
    New=[]
    Component.append(v)
    New.append(v)
    while len(New)!=0:
        Neighbors=[]
        for n in New:
            Neighbors=list(set(Neighbors+pred(sel,n)))
        New=list(set(Neighbors) - set(Component))
        Component=list(set(Component+New))
    return Component

In [37]:
TRANSITIVECLOSUREPRED(G_13,'2')

['3', '2', '1', '4']

In [31]:
pred(G_13,'2')

1
(1,2)
2
7
(4,2)
2


['1', '4']

In [2]:
Graph_dir=r'C:\Users\Mr Nam\Desktop\TP\Graph'
os.listdir(Graph_dir)

['.ipynb_checkpoints',
 'Graph_1_1',
 'Graph_1_12',
 'Graph_1_13',
 'Graph_1_18',
 'Graph_1_29']

In [3]:
Graph_1_1_dir=os.path.join(Graph_dir,'Graph_1_1')
os.listdir(Graph_1_1_dir)

['.ipynb_checkpoints',
 'adjMatrix.txt',
 'arcs.txt',
 'inInMatrix.txt',
 'nodes.txt',
 'outInMatrix.txt']

In [4]:
G_11=dmg(5,10)

In [5]:
G_11.read_nodes(os.path.join(Graph_1_1_dir,'nodes.txt'))
G_11.read_arcs(os.path.join(Graph_1_1_dir,'arcs.txt'))
G_11.read_adjMatrix(os.path.join(Graph_1_1_dir,'adjMatrix.txt'))
G_11.read_inInMatrix(os.path.join(Graph_1_1_dir,'inInMatrix.txt'))
G_11.read_outInMatrix(os.path.join(Graph_1_1_dir,'outInMatrix.txt'))

In [7]:
G_11.display_arc()

List of arc(s)
(1,2)
(2,2)
(2,3)
(2,5)
(3,5)
(4,4)
(4,1)
(4,5)
(5,3)
(5,4)


In [7]:
G.outInMatrix

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 0]], dtype=uint32)

In [8]:
G.inInMatrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=uint32)

In [11]:
G.inInMatrix[G.Nodes.index('5')].sum()

3

In [7]:
deg_in(G,'5')

3

In [5]:
def deg_in(G,v):
    index=G.Nodes.index(v)
    result= G.inInMatrix[G.Nodes.index(v)].sum()
    return result

# Graph 1.1 (trang 2)

In [2]:
G=dmg(5,10)
G.set_node(["1","2","3","4","5"])
G.set_arc(["(1,2)","(2,2)","(2,3)","(2,5)","(3,5)","(4,4)","(4,1)","(4,5)","(5,3)","(5,4)"]);

In [35]:

G.write_nodes(os.path.join(Graph_1_1_dir,'nodes.txt'))
G.write_arcs(os.path.join(Graph_1_1_dir,'arcs.txt'))

In [3]:
G.generate_adjMatrix()
G.generate_in_out_InMatrix()

In [5]:
G.inInMatrix

array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 0]], dtype=uint32)

In [6]:
G.outInMatrix

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=uint32)

In [7]:
G.adjMatrix

array([[0, 1, 0, 0, 0],
       [0, 1, 1, 0, 1],
       [0, 0, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 1, 1, 0]], dtype=uint32)

In [32]:
G.write_adjMatrix(os.path.join(Graph_1_1_dir,'adjMatrix.txt'))
G.write_inInMatrix(os.path.join(Graph_1_1_dir,'inInMatrix.txt'))
G.write_outInMatrix(os.path.join(Graph_1_1_dir,'outInMatrix.txt'))

# Graph 1.12 (trang 11 sách tiếng việt)

In [12]:
Graph_1_12_dir=os.path.join(Graph_dir,'Graph_1_12')
if not os.path.isdir(Graph_1_12_dir):
    os.makedirs(os.path.join(Graph_1_12_dir))

In [6]:
G_12=dmg(6,8)
G_12.set_node(["1","2","3","4","5","6"])
G_12.set_arc(["(1,2)","(2,3)","(2,4)","(3,1)","(4,2)","(4,5)","(5,6)","(6,4)"]);

In [7]:
G_12.generate_adjMatrix()
G_12.generate_in_out_InMatrix()

In [10]:
G_12.adjMatrix

array([[0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0]], dtype=uint32)

In [11]:
G_12.inInMatrix

array([[0, 0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0]], dtype=uint32)

In [12]:
G_12.outInMatrix

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint32)

In [29]:
G_12.TRANSITIVECLOSURESUCC('4')

['2', '6', '3', '1', '4', '5']

In [30]:
G_12.write_arcs(os.path.join(Graph_1_12_dir,'arcs.txt'))
G_12.write_nodes(os.path.join(Graph_1_12_dir,'nodes.txt'))
G_12.write_adjMatrix(os.path.join(Graph_1_12_dir,'adjMatrix.txt'))
G_12.write_inInMatrix(os.path.join(Graph_1_12_dir,'inInMatrix.txt'))
G_12.write_outInMatrix(os.path.join(Graph_1_12_dir,'outInMatrix.txt'))

# Graph 1.13 (trang 12 sách tiếng việt)

In [14]:
Graph_1_13_dir=os.path.join(Graph_dir,'Graph_1_13')
if not os.path.isdir(Graph_1_13_dir):
    os.makedirs(os.path.join(Graph_1_13_dir))

In [14]:
G_13=dmg(9,19)
G_13.set_node(["1","2","3","4","5","6","7","8","9"])
G_13.set_arc(["(1,1)","(1,2)","(1,3)","(2,1)","(2,5)","(3,4)","(4,4)","(4,2)","(4,5)","(5,6)","(5,8)","(6,6)","(6,7)","(6,8)","(7,6)","(7,9)","(8,9)","(9,8)","(9,9)"]);

In [15]:
G_13.generate_adjMatrix()

In [17]:
G_13.adjMatrix

array([[1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=uint32)

In [16]:
G_13.generate_in_out_InMatrix()

In [19]:
G_13.outInMatrix

array([[1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]],
      dtype=uint32)

In [20]:
G_13.inInMatrix

array([[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1]],
      dtype=uint32)

In [21]:
G_13.write_arcs(os.path.join(Graph_1_13_dir,'arcs.txt'))
G_13.write_nodes(os.path.join(Graph_1_13_dir,'nodes.txt'))
G_13.write_adjMatrix(os.path.join(Graph_1_13_dir,'adjMatrix.txt'))
G_13.write_inInMatrix(os.path.join(Graph_1_13_dir,'inInMatrix.txt'))
G_13.write_outInMatrix(os.path.join(Graph_1_13_dir,'outInMatrix.txt'))

In [22]:
G_13.TRANSITIVECLOSURESUCC('5')

['7', '5', '8', '6', '9']

# Graph 1.18 trang 21 sách tiếng việt

In [25]:
Graph_1_18_dir=os.path.join(Graph_dir,'Graph_1_18')
if not os.path.isdir(Graph_1_18_dir):
    os.makedirs(os.path.join(Graph_1_18_dir))

In [2]:
G_18=dmg(6,9)
G_18.set_node(["0","1","2","3","4","5"])
G_18.set_arc(["(0,2)","(0,4)","(1,0)","(2,3)","(2,4)","(3,2)","(3,5)","(4,5)","(5,4)"]);

In [3]:
G_18.generate_adjMatrix()
G_18.generate_in_out_InMatrix()

In [28]:
G_18.adjMatrix

array([[0, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0]], dtype=uint32)

In [29]:
G_18.inInMatrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint32)

In [30]:
G_18.outInMatrix

array([[0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=uint32)

In [31]:
G_18.Weight=[
    [0, 0,  1,  0,  5,  0],
    [3, 0,  0,  0,  0,  0],
    [0, 0,  0,  2,  2,  0],
    [0, 0,  3,  0,  0,  1],
    [0, 0,  0,  0,  0,  2],
    [0, 0,  0,  0,  1,  0]]
G_18.write_Weight(os.path.join(Graph_1_18_dir,'WeightMatrix.txt'))
G_18.Weight

[[0, 0, 1, 0, 5, 0],
 [3, 0, 0, 0, 0, 0],
 [0, 0, 0, 2, 2, 0],
 [0, 0, 3, 0, 0, 1],
 [0, 0, 0, 0, 0, 2],
 [0, 0, 0, 0, 1, 0]]

In [47]:
G_18.write_arcs(os.path.join(Graph_1_18_dir,'arcs.txt'))
G_18.write_nodes(os.path.join(Graph_1_18_dir,'nodes.txt'))
G_18.write_adjMatrix(os.path.join(Graph_1_18_dir,'adjMatrix.txt'))
G_18.write_inInMatrix(os.path.join(Graph_1_18_dir,'inInMatrix.txt'))
G_18.write_outInMatrix(os.path.join(Graph_1_18_dir,'outInMatrix.txt'))

# Graph 1.29 trang 41 sách tiếng anh (rig16)

In [45]:
Graph_1_29_dir=os.path.join(Graph_dir,'Graph_1_29')
if not os.path.isdir(Graph_1_29_dir):
    os.makedirs(os.path.join(Graph_1_29_dir))

In [46]:
G_29=dmg(6,6)
G_29.set_node(["1","2","3","4","5","6"])
G_29.set_arc(["(1,3)","(2,3)","(3,4)","(4,5)","(5,6)","(6,4)"]);

In [86]:
G_29.generate_adjMatrix()
G_29.generate_in_out_InMatrix()

In [50]:
G_29.write_arcs(os.path.join(Graph_1_29_dir,'arcs.txt'))
G_29.write_nodes(os.path.join(Graph_1_29_dir,'nodes.txt'))
G_29.write_adjMatrix(os.path.join(Graph_1_29_dir,'adjMatrix.txt'))
G_29.write_inInMatrix(os.path.join(Graph_1_29_dir,'inInMatrix.txt'))
G_29.write_outInMatrix(os.path.join(Graph_1_29_dir,'outInMatrix.txt'))

In [93]:
def ROYWARSHALL(adjMatrix):
    m=copy.deepcopy(adjMatrix)
    for i in range(len(m)):
        m[i,i]=1
    print(m)
    for k in range(len(m)):
        for i in range(len(m)):
            for j in range(len(m)):
                m[i][j] = m[i][j] or( m[i][k] and m[k][j]);  
    return m

In [92]:
G_29.adjMatrix


array([[0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0]], dtype=uint32)

In [94]:
ROYWARSHALL(G_29.adjMatrix)

[[1 0 1 0 0 0]
 [0 1 1 0 0 0]
 [0 0 1 1 0 0]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]
 [0 0 0 1 0 1]]


array([[1, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]], dtype=uint32)

In [13]:
def min_distance(dist, sptSet):
    min_value = sys.maxsize 
    min_index=-1
    for v in range(len(dist)): 
        if dist[v] < min_value and sptSet[v] == False: 
            min_value = dist[v] 
            min_index = v 
    return min_index 
def printSolution( dist,number_value): 
    print("Vertex \tDistance from Source")
    for node in range(number_value): 
        print (node, "\t", dist[node])
def dijkstra(graph,src): 

    dist = [sys.maxsize] * len(graph)
    dist[src] = 0
    sptSet = [False] * len(graph)

    for cout in range(len(graph)): 

        u = min_distance(dist, sptSet) 
        
        sptSet[u] = True
        
        for v in range(len(graph)): 
            if graph[u][v] > 0 and sptSet[v] == False and dist[v] > dist[u] + graph[u][v]:
                    dist[v] = dist[u] + graph[u][v]
    printSolution(dist,len(graph))

In [26]:
def SPANNINGTREE(Graph):
    def succ(u):
        k=0
        result=[]
        for i in Graph.adjMatrix[Graph.Vertices.index(u)]:
            if i==1:
                result.append(Graph.Vertices[k])
            k+=1
        return result
    Component=[]
    New=[]
    Edges=[]
    Component.append(Graph.Vertices[0])
    New.append(Graph.Vertices[0])

    while len(New)!=0:

        Neighbors=[]
        for n in New:
            Neighbors=list(set(Neighbors+succ(n)))
            New=list(set(Neighbors) - set(Component))
        for v in New:
            for i in range(len(Graph.Edges)):
                comma=int(Graph.Edges[i].find(','))
                a=Graph.Edges[i][1:comma]
                b=Graph.Edges[i][comma+1:-1]
                if (a in Component):
                    if Graph.Edges[i] not in Edges:
                        Edges.append(Graph.Edges[i])
                    Component=list(set(Component+New))

    Component.sort()
    if Component != Graph.Vertices:
        print('Component',Component)
        print('Graph.Nodes',Graph.Vertices)
        return('Error: G is not connected')

    else:
        return(Component,Edges)


In [55]:
Component.sort()
Component

['1', '2', '3', '4', '5', '6', '7', '8', '9']

In [27]:
SPANNINGTREE(G_19)

(['0', '1', '2', '3', '4', '5'],
 ['(0,2)', '(0,4)', '(1,0)', '(2,3)', '(2,4)', '(4,5)', '(3,5)'])

In [58]:
G_18.Nodes

['0', '1', '2', '3', '4', '5']

In [63]:
SPANNINGTREE(G_18)

(['0', '1', '2', '3', '4', '5'],
 ['(1,0)',
  '(0,2)',
  '(0,4)',
  '(2,3)',
  '(2,4)',
  '(4,5)',
  '(3,2)',
  '(3,5)',
  '(5,4)'])

In [93]:
G_18.Arcs= ['(0,2)',
             '(0,4)',
             '(1,0)',
             '(2,3)',
             '(2,4)',
             '(3,5)',
             '(4,5)' ]

In [101]:
G_18.generate_in_out_InMatrix

<bound method direct_multigraph.generate_in_out_InMatrix of <Graph_tool.direct_multigraph object at 0x000002C43F7DAD00>>

In [102]:
G_18.inInMatrix

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0]], dtype=uint32)

In [28]:
G_18.Nodes

['0', '1', '2', '3', '4', '5']

In [ ]:
def generate_InMatrix(self):
    for i in range(len(self.Edges)):
    comma=int(self.Edges[i].find(','))
    a=int(self.Edges[i][1:comma])
    b=int(self.Edges[i][comma+1:-1])

    self.inMatrix[a,i] =1
    self.inMatrix[b,i] =1

In [3]:
G_19=mg(12,11)


In [4]:
G_19.Vertices=['1', '2', '3', '4', '5','6','7','8','9','10','11','12']

In [5]:
G_19.Edges=['(1,2)',
             '(1,3)',
             '(2,4)',
             '(2,5)',
             '(4,8)',
             '(4,9)',
             '(3,6)',
           '(3,7)',
           '(6,10)',
           '(6,11)',
           '(7,12)']

In [6]:
G_19.generate_InMatrix()
G_19.generate_adjMatrix()

In [7]:
G_19.inMatrix

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint32)

In [8]:
G_19.adjMatrix

array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=uint32)

In [9]:
G_19.Vertices

['0', '1', '2', '3', '4', '5']

In [22]:
def succ(u):
    k=0
    result=[]
    for i in G_19.adjMatrix[G_19.Vertices.index(u)]:
        if i==1:
            result.append(G_19.Vertices[k])
        k+=1
    return result

In [23]:
succ('0')

['1', '2', '4']

In [158]:
for i in range(len(G_19.Edges)):
    comma=int(G_19.Edges[i].find(','))
    a=int(G_19.Edges[i][1:comma])
    b=int(G_19.Edges[i][comma+1:-1])

    G_19.inMatrix[a,i] =1
    G_19.inMatrix[b,i] =1


0 2
[[1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
0 4
[[1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
1 0
[[1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
2 3
[[1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
2 4
[[1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 1 1 0 0]
 [0 0 0 1 0 0 0]
 [0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0]]
3 5
[[1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 1 1 0 0]
 [0 0 0 1 0 1 0]
 [0 1 0 0 1 0 0]
 [0 0 0 0 0 1 0]]
4 5
[[1 1 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [1 0 0 1 1 0 0]
 [0 0 0 1 0 1 0]
 [0 1 0 0 1 0 1]
 [0 0 0 0 0 1 1]]


In [159]:
G_19.inMatrix

array([[1, 1, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 1, 1]], dtype=uint32)

In [70]:
G_19=mg(5,7)
G_19.Edges=['(0,2)',
             '(0,4)',
             '(1,0)',
             '(2,3)',
             '(2,4)',
             '(3,5)',
             '(4,5)' ]
G_19.Nodes=G_18.Nodes

In [199]:
def DEPTHFIRSTTRAVERSAL(G,v):
    temp=[]
    def succ(u):
        k=0
        result=[]
        for i in G.adjMatrix[G.Vertices.index(u)]:
            if i==1:
                result.append(G.Vertices[k])
            k+=1
        return result
    componemt=[]
    componemt.append(v)
    print(v)
    while len(componemt)!=len(G.Vertices):
        i=len(componemt)-1
        X=list(set(succ(componemt[i])) - set(componemt))
       # X.sort()
        X.sort(reverse=True)
        if len(X)!=0:
            print(X[-1])
            temp=temp+X[:-1]
        else:
            for i in range(len(temp)-1, -1, -1):
                print(temp[i])
            temp=[]
        while len(X)==0:
            i=i-1
            X=list(set(succ(componemt[i])) - set(componemt))
            X.reverse()
            if len(X)!=0:
                temp=temp+X[:-1]
        for x in X :
            if x not in componemt:
                componemt.append(x)
            print(componemt)
    print(componemt[-1])

In [200]:
DEPTHFIRSTTRAVERSAL(G_19,'1')

1
2
['1', '3']
['1', '3', '2']
4
['1', '3', '2', '5']
['1', '3', '2', '5', '4']
8
['1', '3', '2', '5', '4', '9']
['1', '3', '2', '5', '4', '9', '8']
9
5
3
['1', '3', '2', '5', '4', '9', '8', '7']
['1', '3', '2', '5', '4', '9', '8', '7', '6']
10
['1', '3', '2', '5', '4', '9', '8', '7', '6', '11']
['1', '3', '2', '5', '4', '9', '8', '7', '6', '11', '10']
11
7
['1', '3', '2', '5', '4', '9', '8', '7', '6', '11', '10', '12']
12


In [188]:
componemt.sort(reverse=True)
print(componemt)

['5', '4', '3', '2', '1', '0']


In [185]:
Graph_dir=r'C:\Users\Mr Nam\Desktop\TP\Graph'
Graph_1_18_dir=os.path.join(Graph_dir,'Graph_1_18')

G_18=dmg(6,9)
G_18.read_nodes(os.path.join(Graph_1_18_dir,'nodes.txt'))
G_18.read_arcs(os.path.join(Graph_1_18_dir,'arcs.txt'))
G_18.read_adjMatrix(os.path.join(Graph_1_18_dir,'adjMatrix.txt'))
G_18.read_inInMatrix(os.path.join(Graph_1_18_dir,'inInMatrix.txt'))
G_18.read_outInMatrix(os.path.join(Graph_1_18_dir,'outInMatrix.txt'))

In [71]:
G_18.adjMatrix

array([[0, 0, 0, 0, 0, 1],
       [0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 1, 0, 0]])

In [72]:
G_18.Arcs

['(0,2)',
 '(0,4)',
 '(1,0)',
 '(2,3)',
 '(2,4)',
 '(3,2)',
 '(3,5)',
 '(4,5)',
 '(5,4)']

In [74]:
G_18.Weight

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=uint32)

In [70]:
def min_distance(dist, sptSet):
    min_value = sys.maxsize 
    min_index=-1
    for v in range(len(dist)): 
        if dist[v] < min_value and sptSet[v] == False: 
            min_value = dist[v] 
            min_index = v 
    return min_index 

def printSolution( dist,number_value): 
    print("Vertex \tDistance from Source")
    for node in range(number_value): 
        print (node, "\t", dist[node])

def dijkstra(graph,src): 

    dist = [sys.maxsize] * len(graph)
    dist[src] = 0
    sptSet = [False] * len(graph)

    for cout in range(len(graph)): 

        u = min_distance(dist, sptSet) 
        
        sptSet[u] = True
        
        for v in range(len(graph)): 
            if graph[u][v] > 0 and sptSet[v] == False and dist[v] > dist[u] + graph[u][v]:
                    dist[v] = dist[u] + graph[u][v]
    printSolution(dist,len(graph))

print('dijkstra with figure 1.21')
dijkstra(G_18.Weight,0)

dijkstra with figure 1.21
Vertex 	Distance from Source
0 	 0
1 	 9223372036854775807
2 	 9223372036854775807
3 	 9223372036854775807
4 	 9223372036854775807
5 	 9223372036854775807


In [66]:
v='0'
nam=0


len(G_19.Vertices): 6
componemt: ['0']
1
['2', '4', '1']
len(G_19.Vertices): 6
componemt: ['0', '2', '4', '1']
4
[]
here
['0']
len(G_19.Vertices): 6
componemt: ['0', '2', '4', '1', '5']
5
['3']


In [68]:
componemt

['0', '2', '4', '1', '5', '3']

In [39]:
def succ(u):
    k=0
    result=[]
    for i in G_19.adjMatrix[G_19.Vertices.index(u)]:
        if i==1:
            result.append(G_19.Vertices[k])
        k+=1
    return result


In [38]:
succ(G_19)

['0', '1', '2', '3', '4', '5']

In [19]:
def depth_first_traversal(G,v1):
    def succ(G,u):
        s = []
        u = int(u)
        for i in range(len(G.Vertices)):
            if (G.adjMatrix[u-1,i]==1):
                s.append(G.Vertices[i])
        return s
    comp = list()
    comp.append(v1)
    while len(comp)!=len(G.Vertices):
        i = len(comp)
        X = list()
        s = succ(G,comp[i-1])
        for u in s:
            if u not in comp:
                X.append(u)
        while len(X)==0:
            i = i-1
            s1 = succ(G,comp[i-1])
            for u in s1:
                if u not in comp:
                    X.append(u)
        for u in X:
            comp.append(u)
            break
    print("dãy đỉnh tương ứng là: ")
    print(comp)

In [20]:
depth_first_traversal(G_19,'1')

dãy đỉnh tương ứng là: 
['1', '2', '4', '8', '9', '5', '3', '6', '10', '11', '7', '12']


In [18]:
TESTINGCYCLICITY(G):
    

[1, 2] 0
[2] 1
[0, 3] 2
Graph has a cycle


In [21]:
for i in G_19.Nodes:
    if i != G_19.Nodes[-1]  : 
        print(G_19.deg_in(i),'->', end =" ")
    else:
        print(G_19.deg_in(i))

AttributeError: 'multigraph' object has no attribute 'Nodes'

In [25]:
G_19.inMatrix.sum(axis=1)

array([2, 3, 3, 3, 1, 3, 2, 1, 1, 1, 1, 1], dtype=uint32)

In [26]:
G_19=dmg(12,11)

In [28]:
G_19.set_node(['1', '2', '3', '4', '5','6','7','8','9','10','11','12'])
G_19.set_arc(['(1,2)',
             '(1,3)',
             '(2,4)',
             '(2,5)',
             '(4,8)',
             '(4,9)',
             '(3,6)',
           '(3,7)',
           '(6,10)',
           '(6,11)',
           '(7,12)'])

In [29]:
G_19.generate_adjMatrix()
G_19.generate_in_out_InMatrix()

In [30]:
for i in G_19.Nodes:
    if i != G_19.Nodes[-1]  : 
        print(G_19.deg_in(i),'->', end =" ")
    else:
        print(G_19.deg_in(i))

0 -> 1 -> 1 -> 1 -> 1 -> 1 -> 1 -> 1 -> 1 -> 1 -> 1 -> 1


In [48]:
G_alternative=copy.deepcopy(G_19) 

In [49]:
G_alternative.inInMatrix.sum(axis=1)

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint32)

In [45]:
G_alternative.inInMatrix=np.delete(G_19.inInMatrix, 0,axis=0)

In [73]:
def TESTINGCYCLICITY(G):
    List_del=[]
    G_a=copy.deepcopy(G)
    while 0 in G_a.inInMatrix.sum(axis=1):
        for i in G_a.Nodes:
            if G_a.deg_in(i)==0:
                List_del.append(G_a.Nodes.index(i))
       # G_b=copy.deepcopy(G_a) 
        #G_a.Nodes= del G_a.Nodes[List_del]
        print(type(G_a.Nodes))
        G_a.inInMatrix=np.delete(G_a.inInMatrix, List_del,axis=0)
        #print('G_b.inInMatrix first',G_b.inInMatrix.shape)
        #print(G_b.inInMatrix)
        G_a.inInMatrix=np.delete(G_a.inInMatrix, List_del,axis=1)
        #G_a=copy.deepcopy(G_b)
      #  print('G_b.inInMatrix second',G_b.inInMatrix.shape)
        #print(G_b.inInMatrix)
    return G_a.inInMatrix

In [74]:
TESTINGCYCLICITY(G_19)

<class 'list'>


IndexError: index 11 is out of bounds for axis 0 with size 11

In [ ]:
G_18.node

In [16]:
def TESTINGCYCLICITY(G):
        def source(node, inInMatrix):
            if len(node)==0: return "None"
            for i in node:
                d = 0
                for y in range(len(inInMatrix[0])):
                    d += inInMatrix[int(i) - 1,y]
                if d==0: 
                    return i
            return "None"
        node = list(G.Nodes)
        arc = list(G.Arcs)
        inInMatrix = np.array(G.inInMatrix)
        while source(node, inInMatrix)!="None":
            v = source(node, inInMatrix)
            node.remove(v)
            for i in range(len(arc)):
                comma=int(arc[i].find(','))
                a=int(arc[i][1:comma])
                b=int(arc[i][comma+1:-1])
                if a==int(v) or b==int(v):
                    for j in range(len(G.Nodes)):
                        inInMatrix[j,i] = 0
        if len(node)==0:
            print("Graph has no cycle.")
        else:
            print("Graph has a cycle.")

In [17]:
TESTINGCYCLICITY(G_18)

Graph has a cycle.
